Repository star-bnl/star-sw, pull requests merged in 2022-11, with the labels that each got.

#415 ci: Enable more tests using star-test-data:v6
  .github/workflows/build-pull-request.yml
  tests/joblist.json
Labels: tests

#434 ci: Turn off CI for certain directories
  .github/workflows/build-pull-request.yml
Labels: infrastructure

#440 [root6] StEvent/StEnumerations.cxx fix
  StRoot/StEvent/StEnumerations.cxx
  StRoot/macros/detectorId.C
Labels: ROOT6

#444 [root6] Set attributes on StrangeMuDstMaker in StBFChain, rather than using interpreter to configure
  StRoot/StBFChain/StBFChain.cxx
  StRoot/StStrangeMuDstMaker/StStrangeMuDstMaker.cxx
Labels: ROOT6

#442 [root6] Eliminate crash when creating the MuDst
  StRoot/StMuDSTMaker/COMMON/StMuDstMaker.cxx
  StRoot/StStrangeMuDstMaker/StStrangeMuDst.cc
Labels: ROOT6

#448 [root6] Fix undeclared identifier 'chain' in StarDb/AgMLGeometry/Geometry...C macro
  StarDb/AgMLGeometry/CreateGeometry.h
Labels: ROOT6
