Repository star-bnl/star-sw, pull requests merged in 2022-07, with the labels that each got.

#372 Fix misconfigured alignment correction in #358, change default start time in eTOF
  StRoot/StETofMatchMaker/StETofMatchMaker.cxx
  StRoot/StETofUtil/StETofGeometry.cxx
Labels: bug

#376 [SL22b] Backport #372: Fix misconfigured alignment correction in #358, ...
  StRoot/StETofMatchMaker/StETofMatchMaker.cxx
  StRoot/StETofUtil/StETofGeometry.cxx
Labels: backport

#236 StMuDSTMaker: fixes for TChain::kBigNumber from ROOT6
  StRoot/StMuDSTMaker/COMMON/StMuChainMaker.cxx
  StRoot/StMuDSTMaker/COMMON/StMuChainMaker.h
  StRoot/StStrangeMuDstMaker/StStrangeMuDstMaker.cxx
Labels: ROOT6
